### ISSUE TITLE
Omni One Theme cannot be viewed , throws exception

### ISSUE THREAD

**Issue by Salman-Asif** [vscodethemes/web#237] opened 2022-05-22 17:16 UTC
Omni One Theme by Mhammed Talhaouy cannot be viewed , throws exception on the page
 
```
TypeError: Cannot read properties of undefined (reading 'editorBackground')
    at q (https://vscodethemes.com/build/routes/e/$extensionSlug/$themeSlug-INARMYEZ.js:1:1153)
    at https://vscodethemes.com/build/root-CKBODAAN.js:1:1286
    at Array.map (<anonymous>)
    at a (https://vscodethemes.com/build/root-CKBODAAN.js:1:1172)
    at Zi (https://vscodethemes.com/build/entry.client-SXW5VM5A.js:5:52842)
    at li (https://vscodethemes.com/build/entry.client-SXW5VM5A.js:5:62268)
    at ta (https://vscodethemes.com/build/entry.client-SXW5VM5A.js:9:9566)
    at bs (https://vscodethemes.com/build/entry.client-SXW5VM5A.js:9:933)
    at Kf (https://vscodethemes.com/build/entry.client-SXW5VM5A.js:9:864)
    at st (https://vscodethemes.com/build/entry.client-SXW5VM5A.js:9:724)

```

**Comment by jschr** [comment] 2022-05-23 12:11
Thanks. Duplicate of https://github.com/vscodethemes/web/issues/237

**Closed by jschr** 2022-05-23 12:11 UTC
Labels: duplicate
